name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - closed


jobs:
  build:
    # build on merged PRs
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update nvmrc
      # use basic regex to get Node engine version from package.json
      # will fail if not correctly specified
      run: node -p "require('./package.json').engines.node.match(/\d.*/)[0]" > .nvmrc

    - name: Deploy preview to Netlify
      id: netlify_deploy
      uses: jsmrcaga/action-netlify-deploy@v1.7.2
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_MESSAGE: "Prod deploy ${{ github.ref }}"
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: build
        build_command: npm run build
        install_command: npm ci
