name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    # build on merged PRs
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Node version
      # use basic regex (first found digits and dots) to get Node engine version from package.json
      # will fail if not correctly specified
      run: |
        NODE_VERSION=$(node -p "require('./package.json').engines.node.match(/[\d.]+/)[0]")
        echo "::set-output name=NODE_VERSION::$NODE_VERSION"
      id: get-node-version

    - name: Use Node.js ${{ steps.get-node-version.outputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy preview to Netlify
      id: netlify_deploy
      # see: https://github.com/marketplace/actions/netlify-deploy
      uses: jsmrcaga/action-netlify-deploy@v1.7.2
      with:
        # secret tokens are added in Github project settings under [project]/settings/secrets/actions
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_MESSAGE: "Prod deploy ${{ github.ref }}"
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: build
        build_command: echo "already built app"
        install_command: echo "already installed dependencies"
